// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9xw6RQ7vs2aOKnKg6lpnmC1ox_TxS-VM',
    appId: '1:617871639657:web:476a9a2fe69795d4c74ef8',
    messagingSenderId: '617871639657',
    projectId: 'kacha-ff418',
    authDomain: 'kacha-ff418.firebaseapp.com',
    storageBucket: 'kacha-ff418.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQSO70sxpnyLPX4QitPYgf-UkrBtoo-2A',
    appId: '1:617871639657:android:471099bed854d93bc74ef8',
    messagingSenderId: '617871639657',
    projectId: 'kacha-ff418',
    storageBucket: 'kacha-ff418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEp8MCnKop0VCatxW48suqOtrNjKGtmDQ',
    appId: '1:617871639657:ios:4ef129066a2a00c8c74ef8',
    messagingSenderId: '617871639657',
    projectId: 'kacha-ff418',
    storageBucket: 'kacha-ff418.appspot.com',
    iosBundleId: 'com.example.kacha',
  );
}
